---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: latest

inputs:
  - name: dis-redis

outputs:
  - name: build

caches:
  - path: go/

run:
  path: dis-redis/ci/scripts/build.sh
